resource_group_name = "RG-Challenge"
location = "Spain Central"
subnet_id = "SN-Challenge"
nic_name = "NIC-Challenge"
vm_name = "VM-Challenge"
vm_size = "Standard_B1s"
os_disk_name = "OSDisk-Challenge"
admin_username = "adminuser"
admin_ssh_public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDf6"
image_publisher = "Canonical"
image_offer = "UbuntuServer"
image_sku = "18.04-LTS"
image_version = "latest"
tags = {
    type = "vm"
}