name: Terraform Checks
on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg software-properties-common
          pip install checkov
          wget -O tflint.zip https://github.com/terraform-linters/tflint/releases/download/v0.47.0/tflint_linux_amd64.zip
          unzip tflint.zip && sudo mv tflint /usr/local/bin/
      
      - name: TFLint
        run: tflint --init && tflint --config .tflint.hcl --recursive
      
      - name: Checkov
        run: checkov -d . --config-file .checkov.yml
      
      - name: Terraform Validate
        run: |
          cd environments/dev
          terraform init -backend=false
          terraform validate